/* SVG sticker pack. Each sticker is stickers/<id>.svg. `face` works like in js/props.js: where it sits
   when it snaps onto a face (anchor, offsets and width in eye-to-eye distances).
   Uses `self` so the service worker can read the list too (to keep every sticker available offline). */
self.PBStickers = [
  { id: 'googly-eyes', name: 'Googly eyes', theme: 'party', face: { at: 'eyes', y: 0, s: 2 } },
  { id: 'googly-eye', name: 'Googly eye' },
  { id: 'cat-whiskers', name: 'Cat nose & whiskers', face: { at: 'nose', y: .05, s: 2.6 } },
  { id: 'dog-ears', name: 'Dog ears', theme: 'party', face: { at: 'eyes', y: -1, s: 3.4 } },
  { id: 'dog-nose', name: 'Dog nose', face: { at: 'nose', y: .05, s: .9 } },
  { id: 'dog-tongue', name: 'Dog tongue', face: { at: 'mouth', y: .5, s: .75 } },
  { id: 'pig-nose', name: 'Pig nose', face: { at: 'nose', y: .05, s: .95 } },
  { id: 'clown-nose', name: 'Clown nose', theme: 'halloween party', face: { at: 'nose', s: .6 } },
  { id: 'rosy-cheeks', name: 'Rosy cheeks', face: { at: 'eyes', y: .75, s: 2.6 } },
  { id: 'monocle', name: 'Monocle', face: { at: 'eyes', x: .5, y: .33, s: .95 } },
  { id: 'eye-patch', name: 'Eye patch', theme: 'pirate', face: { at: 'eyes', x: -.13, y: .02, s: 2.8 } },
  { id: 'handlebar', name: 'Handlebar mustache', face: { at: 'lip', s: 1.6 } },
  { id: 'beard', name: 'Beard', theme: 'pirate', face: { at: 'mouth', y: .1, s: 2.2 } },
  { id: 'tiara', name: 'Tiara', theme: 'party', face: { at: 'eyes', y: -1.65, s: 1.7 } },
  { id: 'viking-helmet', name: 'Viking helmet', theme: 'party', face: { at: 'eyes', y: -1.72, s: 3.2 } },
  { id: 'cowboy-hat', name: 'Cowboy hat', theme: 'party', face: { at: 'eyes', y: -1.65, s: 3.4 } },
  { id: 'unicorn-horn', name: 'Unicorn horn', theme: 'party', face: { at: 'eyes', y: -1.96, s: .75 } },
  { id: 'antennae', name: 'Alien antennae', theme: 'halloween party', face: { at: 'eyes', y: -2.2, s: 2.6 } },
  // holiday & theme faces (width `s` and offsets are in eye-to-eye distances; see the top of this file)
  { id: 'birthday-crown', name: 'Birthday crown', theme: 'birthday', face: { at: 'eyes', y: -1.85, s: 2.6 } },
  { id: 'cake-hat', name: 'Cake hat', theme: 'birthday', face: { at: 'eyes', y: -2.09, s: 2.6 } },
  { id: 'party-horn', name: 'Party horn', theme: 'birthday newyear', face: { at: 'mouth', x: 1.06, y: .02, s: 2.2 } },
  { id: 'witch-hat', name: 'Witch hat', theme: 'halloween', face: { at: 'eyes', y: -2.32, s: 3.4 } },
  { id: 'pumpkin-mask', name: 'Jack-o’-lantern mask', theme: 'halloween', face: { at: 'eyes', y: .2, s: 3 } },
  { id: 'vampire-fangs', name: 'Vampire fangs', theme: 'halloween', face: { at: 'mouth', y: .23, s: 1 } },
  { id: 'bat-mask', name: 'Bat mask', theme: 'halloween', face: { at: 'eyes', y: .05, s: 3.2 } },
  { id: 'pilgrim-hat', name: 'Pilgrim hat', theme: 'thanksgiving', face: { at: 'eyes', y: -2.11, s: 2.8 } },
  { id: 'turkey-headband', name: 'Turkey headband', theme: 'thanksgiving', face: { at: 'eyes', y: -2.21, s: 3.6 } },
  { id: 'leaf-crown', name: 'Autumn leaf crown', theme: 'thanksgiving', face: { at: 'eyes', y: -1.4, s: 3.2 } },
  { id: 'santa-hat', name: 'Santa hat', theme: 'christmas', face: { at: 'eyes', y: -2.2, s: 3.4 } },
  { id: 'santa-beard', name: 'Santa beard', theme: 'christmas', face: { at: 'mouth', y: .74, s: 2.8 } },
  { id: 'reindeer-antlers', name: 'Reindeer antlers', theme: 'christmas', face: { at: 'eyes', y: -2.2, s: 3.6 } },
  { id: 'reindeer-nose', name: 'Red reindeer nose', theme: 'christmas', face: { at: 'nose', y: -.02, s: .8 } },
  { id: 'elf-hat', name: 'Elf hat & ears', theme: 'christmas', face: { at: 'eyes', y: -1.37, s: 3.6 } },
  { id: 'uncle-sam-hat', name: 'Stars & stripes hat', theme: 'july4', face: { at: 'eyes', y: -2.44, s: 2.6 } },
  { id: 'flag-glasses', name: 'Flag glasses', theme: 'july4', face: { at: 'eyes', y: 0, s: 2.3 } },
  { id: 'star-boppers', name: 'Star boppers', theme: 'july4 newyear', face: { at: 'eyes', y: -2.1, s: 3 } },
  { id: 'leprechaun-hat', name: 'Leprechaun hat', theme: 'stpat', face: { at: 'eyes', y: -2.16, s: 2.8 } },
  { id: 'ginger-beard', name: 'Leprechaun beard', theme: 'stpat', face: { at: 'mouth', y: .63, s: 2.8 } },
  { id: 'shamrock-glasses', name: 'Shamrock glasses', theme: 'stpat', face: { at: 'eyes', y: 0, s: 2.3 } },
  { id: 'bunny-face', name: 'Bunny nose & teeth', theme: 'easter', face: { at: 'nose', y: .19, s: 2.6 } },
  { id: 'heart-boppers', name: 'Heart boppers', theme: 'valentine', face: { at: 'eyes', y: -2.1, s: 3 } },
  { id: 'pirate-hat', name: 'Pirate hat', theme: 'pirate', face: { at: 'eyes', y: -1.8, s: 3.6 } },
  { id: 'pirate-mask', name: 'Pirate face', theme: 'pirate', face: { at: 'eyes', y: .3, s: 3 } },
  { id: 'masquerade', name: 'Masquerade mask', theme: 'newyear party', face: { at: 'eyes', y: -.25, s: 3.2 } },
  { id: 'birthday-cake', name: 'Birthday cake' },
  { id: 'cupcake', name: 'Cupcake' },
  { id: 'gift', name: 'Gift' },
  { id: 'pizza', name: 'Pizza' },
  { id: 'donut', name: 'Donut' },
  { id: 'ice-cream', name: 'Ice cream' },
  { id: 'disco-ball', name: 'Disco ball' },
  { id: 'microphone', name: 'Microphone' },
  { id: 'fire', name: 'Fire' },
  { id: 'sparkle', name: 'Sparkles' },
  { id: 'rainbow-cloud', name: 'Rainbow' },
  { id: 'lol-badge', name: 'LOL' }
];
