// Rebuilds app/js/emoji-data.js (the full emoji picker list) from the unicode-emoji-json package:
//   npm pack unicode-emoji-json && tar xzf unicode-emoji-json-*.tgz && node scripts/build-emoji.mjs package/data-by-group.json
// Emoji newer than MAX_VERSION are left out because older phones show them as empty boxes.
import fs from 'fs';

const MAX_VERSION = 15.0;
const src = process.argv[2];
if (!src) { console.error('usage: node scripts/build-emoji.mjs path/to/data-by-group.json'); process.exit(1); }
const groups = JSON.parse(fs.readFileSync(src, 'utf8'));
const ICONS = { 'Smileys & Emotion': '😀', 'People & Body': '👋', 'Animals & Nature': '🐶', 'Food & Drink': '🍕',
  'Travel & Places': '✈️', 'Activities': '⚽', 'Objects': '💡', 'Symbols': '❤️', 'Flags': '🏁' };
const out = groups.map(g => ({
  name: g.name, icon: ICONS[g.name] || g.emojis[0].emoji,
  // "emoji name" pairs joined with tabs keeps the file small
  list: g.emojis.filter(e => parseFloat(e.emoji_version) <= MAX_VERSION).map(e => e.emoji + ' ' + e.name).join('\t')
}));
const total = out.reduce((n, g) => n + g.list.split('\t').length, 0);
fs.writeFileSync(new URL('../app/js/emoji-data.js', import.meta.url),
  `/* Generated by scripts/build-emoji.mjs from unicode-emoji-json (MIT) — ${total} emoji up to Emoji ${MAX_VERSION}. */\n` +
  `window.PBEmojiData = ${JSON.stringify(out)};\n`);
console.log(`wrote ${total} emoji`);
